package Pojo;
// Generated Apr 14, 2017 6:01:21 PM by Hibernate Tools 4.3.1



/**
 * Tblattendance generated by hbm2java
 */
public class Tblattendance  implements java.io.Serializable {


     private TblattendanceId id;
     private Boolean daDd;

    public Tblattendance() {
    }

	
    public Tblattendance(TblattendanceId id) {
        this.id = id;
    }
    public Tblattendance(TblattendanceId id, Boolean daDd) {
       this.id = id;
       this.daDd = daDd;
    }
   
    public TblattendanceId getId() {
        return this.id;
    }
    
    public void setId(TblattendanceId id) {
        this.id = id;
    }
    public Boolean getDaDd() {
        return this.daDd;
    }
    
    public void setDaDd(Boolean daDd) {
        this.daDd = daDd;
    }




}


