package Pojo;
// Generated Apr 14, 2017 6:01:21 PM by Hibernate Tools 4.3.1



/**
 * Tblaccount generated by hbm2java
 */
public class Tblaccount  implements java.io.Serializable {


     private String userName;
     private String pass;
     private Integer isTheFisrtTime;
     private Integer isSv;

    public Tblaccount() {
    }

	
    public Tblaccount(String userName) {
        this.userName = userName;
    }
    public Tblaccount(String userName, String pass, Integer isTheFisrtTime, Integer isSv) {
       this.userName = userName;
       this.pass = pass;
       this.isTheFisrtTime = isTheFisrtTime;
       this.isSv = isSv;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Integer getIsTheFisrtTime() {
        return this.isTheFisrtTime;
    }
    
    public void setIsTheFisrtTime(Integer isTheFisrtTime) {
        this.isTheFisrtTime = isTheFisrtTime;
    }
    public Integer getIsSv() {
        return this.isSv;
    }
    
    public void setIsSv(Integer isSv) {
        this.isSv = isSv;
    }




}


