package Pojo;
// Generated Apr 14, 2017 6:01:21 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblattendanceId generated by hbm2java
 */
public class TblattendanceId  implements java.io.Serializable {


     private String maSv;
     private String maMh;
     private Date ngayDd;

    public TblattendanceId() {
    }

    public TblattendanceId(String maSv, String maMh, Date ngayDd) {
       this.maSv = maSv;
       this.maMh = maMh;
       this.ngayDd = ngayDd;
    }
   
    public String getMaSv() {
        return this.maSv;
    }
    
    public void setMaSv(String maSv) {
        this.maSv = maSv;
    }
    public String getMaMh() {
        return this.maMh;
    }
    
    public void setMaMh(String maMh) {
        this.maMh = maMh;
    }
    public Date getNgayDd() {
        return this.ngayDd;
    }
    
    public void setNgayDd(Date ngayDd) {
        this.ngayDd = ngayDd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblattendanceId) ) return false;
		 TblattendanceId castOther = ( TblattendanceId ) other; 
         
		 return ( (this.getMaSv()==castOther.getMaSv()) || ( this.getMaSv()!=null && castOther.getMaSv()!=null && this.getMaSv().equals(castOther.getMaSv()) ) )
 && ( (this.getMaMh()==castOther.getMaMh()) || ( this.getMaMh()!=null && castOther.getMaMh()!=null && this.getMaMh().equals(castOther.getMaMh()) ) )
 && ( (this.getNgayDd()==castOther.getNgayDd()) || ( this.getNgayDd()!=null && castOther.getNgayDd()!=null && this.getNgayDd().equals(castOther.getNgayDd()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMaSv() == null ? 0 : this.getMaSv().hashCode() );
         result = 37 * result + ( getMaMh() == null ? 0 : this.getMaMh().hashCode() );
         result = 37 * result + ( getNgayDd() == null ? 0 : this.getNgayDd().hashCode() );
         return result;
   }   


}


