package Pojo;
// Generated Apr 14, 2017 6:01:21 PM by Hibernate Tools 4.3.1



/**
 * TblestudentSubject generated by hbm2java
 */
public class TblestudentSubject  implements java.io.Serializable {


     private TblestudentSubjectId id;
     private Tblstudent tblstudent;
     private Tblsubject tblsubject;
     private String note;

    public TblestudentSubject() {
    }

	
    public TblestudentSubject(TblestudentSubjectId id, Tblstudent tblstudent, Tblsubject tblsubject) {
        this.id = id;
        this.tblstudent = tblstudent;
        this.tblsubject = tblsubject;
    }
    public TblestudentSubject(TblestudentSubjectId id, Tblstudent tblstudent, Tblsubject tblsubject, String note) {
       this.id = id;
       this.tblstudent = tblstudent;
       this.tblsubject = tblsubject;
       this.note = note;
    }
   
    public TblestudentSubjectId getId() {
        return this.id;
    }
    
    public void setId(TblestudentSubjectId id) {
        this.id = id;
    }
    public Tblstudent getTblstudent() {
        return this.tblstudent;
    }
    
    public void setTblstudent(Tblstudent tblstudent) {
        this.tblstudent = tblstudent;
    }
    public Tblsubject getTblsubject() {
        return this.tblsubject;
    }
    
    public void setTblsubject(Tblsubject tblsubject) {
        this.tblsubject = tblsubject;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


