package Pojo;
// Generated Apr 14, 2017 6:01:21 PM by Hibernate Tools 4.3.1



/**
 * TblestudentSubjectId generated by hbm2java
 */
public class TblestudentSubjectId  implements java.io.Serializable {


     private String maSv;
     private String maMh;

    public TblestudentSubjectId() {
    }

    public TblestudentSubjectId(String maSv, String maMh) {
       this.maSv = maSv;
       this.maMh = maMh;
    }
   
    public String getMaSv() {
        return this.maSv;
    }
    
    public void setMaSv(String maSv) {
        this.maSv = maSv;
    }
    public String getMaMh() {
        return this.maMh;
    }
    
    public void setMaMh(String maMh) {
        this.maMh = maMh;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblestudentSubjectId) ) return false;
		 TblestudentSubjectId castOther = ( TblestudentSubjectId ) other; 
         
		 return ( (this.getMaSv()==castOther.getMaSv()) || ( this.getMaSv()!=null && castOther.getMaSv()!=null && this.getMaSv().equals(castOther.getMaSv()) ) )
 && ( (this.getMaMh()==castOther.getMaMh()) || ( this.getMaMh()!=null && castOther.getMaMh()!=null && this.getMaMh().equals(castOther.getMaMh()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMaSv() == null ? 0 : this.getMaSv().hashCode() );
         result = 37 * result + ( getMaMh() == null ? 0 : this.getMaMh().hashCode() );
         return result;
   }   


}


