package Pojo;
// Generated Apr 14, 2017 6:01:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblstudent generated by hbm2java
 */
public class Tblstudent  implements java.io.Serializable {


     private String maSv;
     private String tenSv;
     private String userName;
     private String tenLop;
     private String gioiTinh;
     private Date ngaySinh;
     private String diaChi;
     private Set tblestudentSubjects = new HashSet(0);

    public Tblstudent() {
    }

	
    public Tblstudent(String maSv) {
        this.maSv = maSv;
    }
    
    public Tblstudent(String maSv, String tenSv, String userName, String tenLop, String gioiTinh, String diaChi) {
       this.maSv = maSv;
       this.tenSv = tenSv;
       this.userName = userName;
       this.tenLop = tenLop;
       this.gioiTinh = gioiTinh;
       this.diaChi = diaChi;
       
    }
   
    
    public Tblstudent(String maSv, String tenSv, String userName, String tenLop, String gioiTinh, Date ngaySinh, String diaChi, Set tblestudentSubjects) {
       this.maSv = maSv;
       this.tenSv = tenSv;
       this.userName = userName;
       this.tenLop = tenLop;
       this.gioiTinh = gioiTinh;
       this.ngaySinh = ngaySinh;
       this.diaChi = diaChi;
       this.tblestudentSubjects = tblestudentSubjects;
    }
   
    public String getMaSv() {
        return this.maSv;
    }
    
    public void setMaSv(String maSv) {
        this.maSv = maSv;
    }
    public String getTenSv() {
        return this.tenSv;
    }
    
    public void setTenSv(String tenSv) {
        this.tenSv = tenSv;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getTenLop() {
        return this.tenLop;
    }
    
    public void setTenLop(String tenLop) {
        this.tenLop = tenLop;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public Set getTblestudentSubjects() {
        return this.tblestudentSubjects;
    }
    
    public void setTblestudentSubjects(Set tblestudentSubjects) {
        this.tblestudentSubjects = tblestudentSubjects;
    }




}


