package Pojo;
// Generated Apr 14, 2017 6:01:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblsubject generated by hbm2java
 */
public class Tblsubject  implements java.io.Serializable {


     private String maMh;
     private String tenMh;
     private Set tblestudentSubjects = new HashSet(0);

    public Tblsubject() {
    }

	
    public Tblsubject(String maMh) {
        this.maMh = maMh;
    }
    public Tblsubject(String maMh, String tenMh, Set tblestudentSubjects) {
       this.maMh = maMh;
       this.tenMh = tenMh;
       this.tblestudentSubjects = tblestudentSubjects;
    }
   
    public String getMaMh() {
        return this.maMh;
    }
    
    public void setMaMh(String maMh) {
        this.maMh = maMh;
    }
    public String getTenMh() {
        return this.tenMh;
    }
    
    public void setTenMh(String tenMh) {
        this.tenMh = tenMh;
    }
    public Set getTblestudentSubjects() {
        return this.tblestudentSubjects;
    }
    
    public void setTblestudentSubjects(Set tblestudentSubjects) {
        this.tblestudentSubjects = tblestudentSubjects;
    }




}


