package Pojo;
// Generated Apr 14, 2017 6:01:21 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tbltimetable generated by hbm2java
 */
public class Tbltimetable  implements java.io.Serializable {


     private String maTkb;
     private String monHoc;
     private Date ngayBd;
     private Date ngayKt;
     private Integer soTuan;
     private String thu;
     private Date gioBd;
     private Date gioKt;
     private String phongHoc;

    public Tbltimetable() {
    }

	
    public Tbltimetable(String maTkb) {
        this.maTkb = maTkb;
    }
    public Tbltimetable(String maTkb, String monHoc, Date ngayBd, Date ngayKt, Integer soTuan, String thu, Date gioBd, Date gioKt, String phongHoc) {
       this.maTkb = maTkb;
       this.monHoc = monHoc;
       this.ngayBd = ngayBd;
       this.ngayKt = ngayKt;
       this.soTuan = soTuan;
       this.thu = thu;
       this.gioBd = gioBd;
       this.gioKt = gioKt;
       this.phongHoc = phongHoc;
    }
   
    public String getMaTkb() {
        return this.maTkb;
    }
    
    public void setMaTkb(String maTkb) {
        this.maTkb = maTkb;
    }
    public String getMonHoc() {
        return this.monHoc;
    }
    
    public void setMonHoc(String monHoc) {
        this.monHoc = monHoc;
    }
    public Date getNgayBd() {
        return this.ngayBd;
    }
    
    public void setNgayBd(Date ngayBd) {
        this.ngayBd = ngayBd;
    }
    public Date getNgayKt() {
        return this.ngayKt;
    }
    
    public void setNgayKt(Date ngayKt) {
        this.ngayKt = ngayKt;
    }
    public Integer getSoTuan() {
        return this.soTuan;
    }
    
    public void setSoTuan(Integer soTuan) {
        this.soTuan = soTuan;
    }
    public String getThu() {
        return this.thu;
    }
    
    public void setThu(String thu) {
        this.thu = thu;
    }
    public Date getGioBd() {
        return this.gioBd;
    }
    
    public void setGioBd(Date gioBd) {
        this.gioBd = gioBd;
    }
    public Date getGioKt() {
        return this.gioKt;
    }
    
    public void setGioKt(Date gioKt) {
        this.gioKt = gioKt;
    }
    public String getPhongHoc() {
        return this.phongHoc;
    }
    
    public void setPhongHoc(String phongHoc) {
        this.phongHoc = phongHoc;
    }




}


